export const GET_FLOWERS = 'GET_FLOWERS'
export const GET_BASKETS = 'GET_BASKETS'
export const GET_NOTECARD = 'GET_NOTECARD'

export const ADD_FLOWERS = 'ADD_FLOWERS'
export const DELETE_FLOWERS = 'DELETE_FLOWERS'

export const POST_LOGIN = 'POST_LOGIN'
export const POST_SIGNUP = 'POST_SIGNUP'
export const USER_LOADED = 'USER_LOADED'
export const USER_LOADING = 'USER_LOADING'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const GET_HAPPY = 'GET_HAPPY'
export const GET_GRATITUDE = 'GET_GRATITUDE'
export const GET_LOVE = 'GET_LOVE'
export const GET_SYMPATHY = 'GET_SYMPATHY'

export const ITEMS_LOADING = 'ITEMS_LOADING'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
